Feature/inicio
monotera/FluxWebPage pull request #1
Opened 2020-12-31 12:49 UTC by Manuel-2011

Se termina el componente home, se le añade contenido responsive por medio del break-point "breakpoint-columns" y el uso de fuentes en tamaño em.
Las fuentes usadas se estandarizan en font.scss al igual que los colores que se definen en _variables.scss.

2020-12-31 18:37 UTC, monotera requested changes

2020-12-31 18:37 UTC, monotera commented on code/public/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;700&display=swap" rel="stylesheet">
Estos ya no se necesitarian debido a que los fonts estan dentro del codigo

2020-12-31 18:37 UTC, monotera commented on code/src/components/Home.vue
> +    @media (max-width: $breakpoint-columns) {
Ya que estamos manejando Sass se deberian de encapsular los estilos por ejemplo 
```      
 Button { 
        padding: 10px 20px;
        border: 3px solid $main-font-color;
        color: $main-font-color;
        background-color: $main-background-color;
        cursor: pointer;
        font-family: 'headers-font';
        transition: 0.5s;
        font-size: 10px;    
        &:hover {
            code
        }
        @media (max-width: $breakpoint-columns) {
               code
         }
    }
```

2021-01-01 23:25 UTC, Manuel-2011 commented on code/public/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;700&display=swap" rel="stylesheet">
Listo las voy a eliminar.

2021-01-01 23:36 UTC, Manuel-2011 commented on code/src/components/Home.vue
> +    @media (max-width: $breakpoint-columns) {
Me parece bien, traté de encapsular los estilos en los que usé el mismo selector.

2021-01-02 21:51 UTC, monotera commented
Me parecen bien los cambios, lo único es que note que le das estilo a  los h1 y a button. entonces seria mejor si pones el style como scoped o de pronto utilizar una clase para que no vaya a afectar otros h1 o buttons. Lo demás me parece que esta bien.

2021-01-02 21:51 UTC, monotera approved these changes

2021-01-03 22:28 UTC, merged